### ISSUE TITLE
`spawn ENAMETOOLONG` when trying to process too many files or files with long pathes

### ISSUE THREAD

**Issue by goraSi** [jjwilly16/node-pdftk#5]
I've got an error Fatal error: spawn ENAMETOOLONG when trying to process too many files or files has too long pathes.

Is it possible to implement same solution as here to use stdin:

https://github.com/dbushell/grunt-svg2png/pull/25/commits/e5f57c7bf1c9e498f9fac78ad0f39f05870d2a0a

**Comment by jjwilly16** [comment]
I'd like to look into this, but probably won't have time until after the holidays. I'll update this hopefully next month sometime.

 In the meantime, feel free to submit a pull request if you have this implemented.

**Comment by jjwilly16** [comment]
This is a common Windows filesystem limitation: [https://support.microsoft.com/sv-se/help/830473/command-prompt-cmd--exe-command-line-string-limitation](https://support.microsoft.com/sv-se/help/830473/command-prompt-cmd--exe-command-line-string-limitation).

I considered your suggested solution, but ran into a road block there. In the [PdfTk docs](https://www.pdflabs.com/docs/pdftk-man-page/#dest-input-files) it states that you can pass **a single PDF** into PdfTk via stdin. Since it is very common to pass in multiple source PDFs with this tool, it doesn't look possible to pass them through stdin.

It looks like you may have to batch your files into the tool. Sorry I couldn't be of more help.
